version: "3.9"

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus3
    restart: unless-stopped
    ports:
      - "8081:8081"       # Web UI and API
      - "8002:8002"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false  # disables random admin password generation (optional)

volumes:
  nexus-data:
    driver: local
